services:

  # backend database for website
  postgres:
    environment:
      POSTGRES_DB: backend
      POSTGRES_PASSWORD: 703f9
      POSTGRES_USER: user
    build: 
      context: . 
      dockerfile: images/postgres.Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U user"]
    ports:
      - "5432:5432"

  # pgadmin gui for database
  pgadmin:
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
      PGPASSFILE: /home/pgadmin/pgpass
      GADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    depends_on:
      postgres:
        condition: service_healthy
    build: 
      context: . 
      dockerfile: images/pgadmin.Dockerfile
    ports:
      - "5050:5050"

  # # rusty website backend
  # website:
  #   image: website
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   build: 
  #     context: . 
  #     dockerfile: images/website.Dockerfile
  #   ports:
  #     - "8080:8080"

